# This is a basic workflow to help you get started with Actions

name: ReleaseSDK

# Set to trigger only on new tag added
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Release SDK 
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      
      # This will set latest tag version and print it
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      # This will update the podspec version in the file
      - name: Update PodSpec 
        run: sed -i.bu 's/spec.version      =.*/spec.version      = ${{ steps.get_version.outputs.VERSION }}/' TestLibN.podspec
        
      - name: Show PodSpec Updated
        run: |
          echo "$(<TestLibN.podspec)"
          
      # This should lint the current pod
      - name: Lint Pod
        run: pod spec lint --verbose --allow-warnings
      
      # This should publish the pod with the latest version
      - name: Publish Trunk
        run: |
          echo Will publish after this
