# This is a basic workflow to help you get started with Actions

name: ReleaseSDK

# Set to trigger only on new tag added
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Release SDK 
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # This will update the podspec version in the file
      - name: Update PodSpec 
        run: |
          sed -i "/spec.version      =/c\spec.version      = '${GITHUB_REF##*/}'" TestLibN.podspec
          
      # This should lint the current pod
      - name: Lint Pod
        run: pod spec lint --verbose --allow-warnings
      
      # This should publish the pod with the latest version
      - name: Publish Trunk
        run: |
          echo Will publish after this
